In [2]:
import numpy as np
import pandas as pd

import iqplot

import colorcet

import bokeh.io
import bokeh.models
bokeh.io.output_notebook()

Loading BokehJS ...

In [23]:
df = pd.read_csv('../data/bee_sperm.csv', comment='#')
df.head()

Specimen Treatment Environment  TreatmentNCSS Sample ID  Colony  Cage  \
0       227   Control        Cage              1    C2-1-1       2     1   
1       228   Control        Cage              1    C2-1-2       2     1   
2       229   Control        Cage              1    C2-1-3       2     1   
3       230   Control        Cage              1    C2-1-4       2     1   
4       231   Control        Cage              1    C2-1-5       2     1   

   Sample  Sperm Volume per 500 ul  Quantity  ViabilityRaw (%)    Quality  \
0       1                  2150000   2150000  96.7263814616756  96.726381   
1       2                  2287500   2287500  96.3498079760595  96.349808   
2       3                    87500     87500             98.75  98.750000   
3       4                  1875000   1875000  93.2874208336941  93.287421   
4       5                  1587500   1587500  97.7925061050061  97.792506   

   Age (d)  Infertil  AliveSperm  Quantity Millions  Alive Sperm Millions  \
0       14         0     2079617             2.1500              2.079617   
1       14         0     2204001             2.2875              2.204001   
2       14         0       86406             0.0875              0.086406   
3       14         0     1749139             1.8750              1.749139   
4       14         0     1552456             1.5875              1.552456   

   Dead Sperm Millions  
0             0.070383  
1             0.083499  
2             0.001094  
3             0.125861  
4             0.035044

In [49]:
p = iqplot.ecdf(
    df,
    q='Alive Sperm Millions',
    cats='Treatment',
    conf_int=True,
    n_bs_reps=100_000,
)

bokeh.io.show(p)

In [26]:
df.groupby('Treatment')['Alive Sperm Millions'].mean().reset_index()

Treatment  Alive Sperm Millions
0    Control              1.872777
1  Pesticide              1.299748

In [27]:
ctrl = df.loc[df['Treatment']=='Control', 'Alive Sperm Millions'].values
pest = df.loc[df['Treatment']=='Pesticide', 'Alive Sperm Millions'].values

In [35]:
def draw_bs_sample(data):
    return np.random.choice(data, size=len(data))

In [36]:
import scipy.special

In [37]:
def draw_bs_reps(data, stat_fun, size=1, args=()):
    return np.array([stat_fun(draw_bs_sample(data), *args) for _ in range(size)])

In [45]:
bs_reps_ctrl = draw_bs_reps(ctrl, np.median, size=100_000)
bs_reps_pest = draw_bs_reps(pest, np.median, size=100_000)

In [46]:
np.percentile(bs_reps_ctrl, [2.5, 97.5])

array([1.627705, 2.106079])

In [47]:
np.percentile(bs_reps_pest, [2.5, 97.5])

array([0.9562305, 1.4785335])

In [51]:
np.percentile(bs_reps_ctrl - bs_reps_pest, [0.5, 99.5])

array([0.176789, 1.161101])